plugins { id 'org.jetbrains.kotlin.jvm' }

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

dependencies {
	implementation project(':shared')
	testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

kotlin { compilerOptions { freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property' } }

tasks.named('test') { useJUnitPlatform() }
